---
title: "Guidelines"
author: "KMicha71"
date: "2 8 2019"
output:
  html_document: 
    keep_md: true
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Guidelines

### General

* RStudio with R markdown is needed for execution
* language is english
* use utf-8 encoding
* number format is english (1.000) - use point, no comma!

### License
 
* Prefered license is Apache 2.0

### Geographic Foci

* Germany
    * box: 5,45 / 15,55
* Europe
* ...

### Time Resolution

* yearly
* monthly
* ...

### Generated geoJSON files

* https://geojson.org/


### Generated CSV files

* use descriptive, quoted header line
* use really comma as seperator
* quote strings, escape quote signes inside of them
* Reserved columns
    * year: integer 
    * month: integer 1..12
    * time: float: year with fractions (i.e. year + (month-1)/12)

### Used R-libraries

* ggplot2 (Plotting)
* SCI (SPI generation)

### Python code

* smaller chunks can be added directly
* larger should be called via shell
* version is 3.x
* i.e. https://www.spyder-ide.org/


```{python python-direct, python.reticulate = FALSE}
print("Hello from chunk directly")
```

```{sh python-file}
python ./source/hello.py
```
See also https://rstudio.github.io/reticulate/articles/r_markdown.html

### Shell-scripting

* unix/linux based
* install/use cygwin on Windows: https://www.cygwin.com/
* use wget -q -P download <url> to download files in subdirectory if not direct target

### Visualisation

* Add R code to visualize some of the data

